Repository germanbrew/terraform-provider-hetznerdns, pull requests merged in 2024-05, with the labels that each got.

#2 Refactoring and code adjustments
  INSTALL.md
  README.md
  RELEASING.md
  go.mod
  hetznerdns/api/client.go
  hetznerdns/api/client_test.go
  hetznerdns/data_source_zone.go
  hetznerdns/primary_server.go
  hetznerdns/provider.go
  hetznerdns/resource_record.go
  hetznerdns/resource_zone.go
  main.go
Labels: Kind/Dependency, Kind/Documentation

#12 Update test.yaml
  .github/workflows/test.yaml
Labels: Kind/CICD

#13 Minor adjustments in docs
  README.md
Labels: Kind/Documentation

#17 Adjust docs
  README.md
  docs/resources/hetznerdns_record.md
Labels: Kind/Documentation

#18 Fix typo
  docs/resources/hetznerdns_record.md
Labels: Kind/Documentation

#24 Add example for SRV records
  README.md
Labels: Kind/Documentation

#25 Add srv example to docs
  README.md
Labels: Kind/Documentation

#28 Add handler for TXT records with more that 255 bytes length
  hetznerdns/primary_server_test.go
  hetznerdns/resource_record.go
  hetznerdns/resource_record_test.go
Labels: Kind/Enhancement

#30 Adjust README.md
  README.md
Labels: Kind/Documentation

#31 Add provider options to set max retries
  .github/workflows/test.yaml
  Makefile
  docs/index.md
  internal/provider/provider.go
  internal/provider/record_resource.go
  internal/provider/zone_resource.go
Labels: Kind/Enhancement

#35 Add txt handler note to docs
  README.md
Labels: Kind/Documentation

#42 Enable max line length and more linter
  .editorconfig
  .golangci.yml
  Makefile
  docs/functions/idna.md
  internal/api/client.go
  internal/api/client_test.go
  internal/api/retry.go
  internal/api/utils.go
  internal/api/zone_test.go
  internal/provider/idna_function.go
  internal/provider/idna_function_test.go
  internal/provider/primary_server_resource.go
  internal/provider/primary_server_resource_test.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/record_resource.go
  internal/provider/record_resource_test.go
  internal/provider/zone_data_source.go
  internal/provider/zone_data_source_test.go
  internal/provider/zone_resource.go
  internal/utils/txt.go
  internal/utils/txt_test.go
Labels: Kind/CICD

#46 Add CI job for cleanup old DNS zones
  .github/workflows/cleanup_zones.yaml
Labels: Kind/CICD

#38 Add provider flag for txt 255 limit feature
  README.md
  docs/index.md
  internal/provider/primary_server_resource.go
  internal/provider/provider.go
  internal/provider/record_resource.go
  internal/provider/zone_data_source.go
  internal/provider/zone_resource.go
Labels: Kind/Enhancement

#49 Allow enable_txt_formatter=false and ensure naming
  README.md
  docs/index.md
  examples/provider/provider.tf
  internal/provider/primary_server_resource.go
  internal/provider/provider.go
  internal/provider/record_resource.go
  internal/provider/zone_data_source.go
  internal/provider/zone_resource.go
Labels: Kind/Enhancement

#50 Add development section to README.md
  README.md
Labels: Kind/Documentation

#51 Fix typo and adjust docs
  docs/index.md
  internal/provider/provider.go
Labels: Kind/Documentation

#53 Add migration guide
  README.md
  docs/guides/migration-from-timohirt-hetznerdns.md
  templates/guides/migration-from-timohirt-hetznerdns.md
Labels: Kind/Documentation

#54 Add link in Readme to new migration guide
  README.md
Labels: Kind/Documentation

#55 Adjust migration guide
  docs/guides/migration-from-timohirt-hetznerdns.md
  templates/guides/migration-from-timohirt-hetznerdns.md
Labels: Kind/Documentation

#57 Set minimum release age for packages
  renovate.json
Labels: Kind/CICD

#59 Fix minimumReleaseAge for Renovate
  renovate.json
Labels: Kind/CICD

#60 Add release template
  .github/release.yml
Labels: Kind/Documentation

#61 Adjust documenation
  Makefile
  README.md
Labels: Kind/Documentation

#62 Add links to badges
  README.md
Labels: Kind/Documentation

#65 CI: Add spell checker
  .github/workflows/spelling.yaml
  RELEASING.md
  internal/utils/txt_test.go
Labels: Kind/CICD
