Repository germanbrew/terraform-provider-hetznerdns, pull requests merged in 2024-06, with the labels that each got.

#67 Add tfproviderlint
  .github/workflows/test.yaml
  go.mod
  internal/api/client.go
  internal/api/client_test.go
  internal/api/retry.go
  internal/provider/primary_server_resource_test.go
  internal/provider/provider.go
  internal/provider/record_resource_test.go
  internal/provider/zone_data_source_test.go
  internal/provider/zone_resource_test.go
Labels: Kind/CICD

#64 Add hetznerdns_records datasource
  Makefile
  docs/data-sources/records.md
  examples/data-sources/hetznerdns_record/data-source.tf
  internal/api/record.go
  internal/provider/provider.go
  internal/provider/records_data_source.go
  internal/provider/records_data_source_test.go
Labels: Kind/Feature

#69 Add section for dependencies in release template
  .github/release.yml
Labels: Kind/Documentation

#71 Fix import example for resource hetznerdns_record
  docs/resources/record.md
  examples/resources/hetznerdns_record/import.sh
Labels: Kind/Documentation

#79 Add yaml schemas
  .golangci.yml
  .goreleaser.yml
Labels: Kind/CICD

#80 Adjust link to timeouts documentation
  docs/data-sources/records.md
  docs/data-sources/zone.md
  docs/resources/primary_server.md
  docs/resources/record.md
  docs/resources/zone.md
  internal/provider/primary_server_resource.go
  internal/provider/record_resource.go
  internal/provider/records_data_source.go
  internal/provider/zone_data_source.go
  internal/provider/zone_resource.go
Labels: Kind/Documentation

#84 chore: update Go version to 1.22.4
  go.mod
Labels: Kind/Dependency
