Repository germanbrew/terraform-provider-hetznerdns, pull requests merged in 2024-12, with the labels that each got.

#149 fix: handle rate limit exceeded error
  internal/api/client.go
Labels: Kind/Enhancement

#153 docs: remove escaping example
  docs/resources/record.md
  internal/provider/record_resource.go
Labels: Kind/Documentation

#151 feat: add hetznerdns_nameserver data source
  docs/data-sources/nameservers.md
  docs/resources/zone.md
  examples/data-sources/hetznerdns_nameservers/data-source.tf
  examples/resources/hetznerdns_zone/resource.tf
  internal/api/nameserver.go
  internal/provider/nameserver_data_source.go
  internal/provider/nameserver_data_source_test.go
  internal/provider/provider.go
Labels: Kind/Documentation, Kind/Feature

#154 ci: test for terraform v1.10
  .github/workflows/test.yaml
Labels: Kind/CICD

#155 docs: remove wrong reference
  docs/guides/investigating-rate-limits.md
  templates/guides/investigating-rate-limits.md
Labels: Kind/Documentation

#156 feat: set default value for nameserver data source
  docs/data-sources/nameservers.md
  examples/data-sources/hetznerdns_nameservers/data-source.tf
  internal/provider/nameserver_data_source.go
  internal/provider/nameserver_data_source_test.go
Labels: Kind/Enhancement

#158 test: add test for emoji domain
  internal/provider/idna_function_test.go
Labels: Kind/CICD

#160 docs: enhance documentation of idna function
  docs/functions/idna.md
  internal/provider/idna_function.go
Labels: Kind/Documentation
